image:
  pullPolicy: IfNotPresent
  repository: dennisezeanya/ailg_jumblerepo
  tag: 1.0

NODE_ENV: production
DATABASE_URL: mongodb+srv://glia:glia1234@ailgdb.q9ohgvp.mongodb.net/test
API_KEY: testing

Port: 8000

# DATABASE_URL and API_KEY should be kept secret/omitted but for this test I provided it. 